spring:
  application:
    name: oauth
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 872513551359-nv7j7buqk9b4udj444kbb8u240r2o3om.apps.googleusercontent.com
            client-secret: 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
logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate: DEBUG
    com:
      example:
        oauth: DEBUG